### ISSUE TITLE
ERROR:  Could not find a valid gem 'cinc-auditor-bin' (= 4.18.51) in any repository

### ISSUE THREAD

**Issue by arunalakmal** [darkbitio/mkit#7]
I was getting this error when building an docker image locally,  strange thing is it was succeeded day before yesterday. Any idea?

`[ec2-user@ip-10-0-1-100 mkit]$ make build
Building arunalakmal/mkit:latest
Sending build context to Docker daemon  4.006MB
Step 1/39 : FROM ruby:2.6.5-alpine3.11
 ---> 59d4ec426ed6
Step 2/39 : ARG VERSION=4.18.51
 ---> Using cache
 ---> 4b01f67fa580
Step 3/39 : ARG GEM_SOURCE=https://rubygems.org
 ---> Using cache
 ---> 64b67897db0b
Step 4/39 : ARG RUNUSER=node
 ---> Using cache
 ---> 9a8a483ae518
Step 5/39 : ARG UIDIR="ui"
 ---> Using cache
 ---> 455129051d28
Step 6/39 : ARG AUDITDIR="audit"
 ---> Using cache
 ---> e0118f54bb49
Step 7/39 : ARG PROFILEDIR="profiles"
 ---> Using cache
 ---> 001471de4aab
Step 8/39 : ARG NODE_CHECKSUM="7606d86e842b710e4321fe1c7f7a32a8e145f5e0659de406399cda5a37411d92"
 ---> Using cache
 ---> 4d3f86915a32
Step 9/39 : ARG YARN_GPG_KEY="6A010C5166006599AA17F08146C2130DFD2497F5"
 ---> Using cache
 ---> ff372fdd5624
Step 10/39 : ENV NODE_VERSION 12.16.1
 ---> Using cache
 ---> 654b21eaf9aa
Step 11/39 : ENV YARN_VERSION 1.22.0
 ---> Using cache
 ---> 7d9e3560ad46
Step 12/39 : ENV NODE_ENV=production
 ---> Using cache
 ---> 72dcd28e169f
Step 13/39 : RUN apk add --update build-base gcc musl-dev openssl-dev libstdc++ libxml2-dev libffi-dev bash gnupg tar git openssh-client python3-dev python3 py3-pip curl jq &&     python3 -m pip install --upgrade pip &&     curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator &&     chmod +x ./aws-iam-authenticator &&     mv ./aws-iam-authenticator /usr/local/bin &&     rm -rf /tmp/* &&     rm -rf /var/cache/apk/* &&     rm -rf /var/tmp/*
 ---> Using cache
 ---> 931f60648f8b
Step 14/39 : RUN curl -fsSLO --compressed "https://unofficial-builds.nodejs.org/download/release/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64-musl.tar.xz" &&     echo "${NODE_CHECKSUM}  node-v${NODE_VERSION}-linux-x64-musl.tar.xz" | sha256sum -c - &&     tar -xJf "node-v${NODE_VERSION}-linux-x64-musl.tar.xz" -C /usr/local --strip-components=1 --no-same-owner &&     ln -s /usr/local/bin/node /usr/local/bin/nodejs &&     rm -f "node-v${NODE_VERSION}-linux-x64-musl.tar.xz" &&     node --version &&     npm --version
 ---> Using cache
 ---> 64355ebc3d74
Step 15/39 : RUN apk add --no-cache --virtual .build-deps-yarn &&     gpg --batch --keyserver hkp://pgp.mit.edu:80 --recv-keys "${YARN_GPG_KEY}" &&     curl -fsSLO --compressed "https://yarnpkg.com/downloads/${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz" &&     curl -fsSLO --compressed "https://yarnpkg.com/downloads/${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz.asc" &&     gpg --batch --verify yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz &&     mkdir -p /opt &&     tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ &&     ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn &&     ln -s /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg &&     rm yarn-v$YARN_VERSION.tar.gz yarn-v$YARN_VERSION.tar.gz.asc &&     apk del .build-deps-yarn &&     yarn --version
 ---> Running in 001206d80b17
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/1) Installing .build-deps-yarn (20200425.041207)
OK: 341 MiB in 96 packages
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 1646B01B86E50310: public key "Yarn Packaging <yarn@dan.cx>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Wed Feb  5 12:55:14 2020 UTC
gpg:                using RSA key 6D98490C6F1ACDDD448E45954F77679369475BAA
gpg: Good signature from "Yarn Packaging <yarn@dan.cx>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
     Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
(1/1) Purging .build-deps-yarn (20200425.041207)
OK: 341 MiB in 95 packages
1.22.0
Removing intermediate container 001206d80b17
 ---> b4d5848c1560
Step 16/39 : RUN addgroup -g 1000 ${RUNUSER} &&     adduser -u 1000 -G ${RUNUSER} -s /bin/sh -D ${RUNUSER}
 ---> Running in a7c7d270299d
Removing intermediate container a7c7d270299d
 ---> 4f82a0b81920
Step 17/39 : WORKDIR /home/${RUNUSER}
 ---> Running in c9e3de7b1ad3
Removing intermediate container c9e3de7b1ad3
 ---> 0ebc180fdfdf
Step 18/39 : USER ${RUNUSER}
 ---> Running in 4e5fa7ff5d62
Removing intermediate container 4e5fa7ff5d62
 ---> 42f8011727c0
Step 19/39 : RUN mkdir -p /home/${RUNUSER}/${UIDIR} /home/${RUNUSER}/${AUDITDIR} /home/${RUNUSER}/${PROFILEDIR}
 ---> Running in 6d8ae3011a9b
Removing intermediate container 6d8ae3011a9b
 ---> a66d61dd51ca
Step 20/39 : ENV PATH="/home/${RUNUSER}/.gem/ruby/2.6.0/bin:${PATH}"
 ---> Running in a62ecc042c6e
Removing intermediate container a62ecc042c6e
 ---> fbf8c66dd76c
Step 21/39 : RUN gem install --user-install --no-document --source ${GEM_SOURCE} --version ${VERSION} inspec &&     gem install --user-install --no-document --source ${GEM_SOURCE} --version ${VERSION} cinc-auditor-bin &&     gem install --user-install --no-document jsonl train-kubernetes &&     cinc-auditor plugin install train-kubernetes &&     sed -ie 's#"= 0#"0#g' /home/${RUNUSER}/.inspec/plugins.json
 ---> Running in 7a3ddc20708f
Successfully installed public_suffix-4.0.4
Successfully installed addressable-2.7.0
Successfully installed mixlib-shellout-3.0.9
Successfully installed net-ssh-5.2.0
Successfully installed net-scp-2.0.0
Successfully installed train-core-3.2.28
Successfully installed builder-3.2.4
Successfully installed erubi-1.9.0
Building native extensions. This could take a while...
Successfully installed ffi-1.12.2
Successfully installed gssapi-1.3.0
Successfully installed gyoku-1.3.1
Successfully installed httpclient-2.8.3
Successfully installed multi_json-1.14.1
Successfully installed little-plugger-1.1.4
Successfully installed logging-2.2.2
Successfully installed nori-2.6.0
Successfully installed rubyntlm-0.6.2
Successfully installed winrm-2.3.4
Successfully installed rubyzip-1.3.0
Successfully installed winrm-fs-1.3.3
Successfully installed train-winrm-0.2.6
Successfully installed concurrent-ruby-1.1.6

HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

If you are upgrading your Rails application from an older version of Rails:

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.

If you are starting a NEW Rails application, you can ignore this notice.

For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

Successfully installed i18n-1.8.2
Successfully installed thread_safe-0.3.6
Successfully installed tzinfo-1.2.7
Successfully installed activesupport-5.2.4.2
Successfully installed inifile-3.0.0
Building native extensions. This could take a while...
Successfully installed unf_ext-0.0.7.2
Successfully installed multipart-post-2.1.1
Successfully installed faraday-0.17.3
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.20190701
Successfully installed http-cookie-1.0.3
Successfully installed faraday-cookie_jar-0.0.6
Successfully installed timeliness-0.3.10
Successfully installed ms_rest-0.7.6
Successfully installed ms_rest_azure-0.11.2
Successfully installed azure_graph_rbac-0.17.1
Successfully installed azure_mgmt_key_vault-0.17.5
Successfully installed azure_mgmt_resources-0.17.8
Successfully installed azure_mgmt_security-0.18.0
Successfully installed azure_mgmt_storage-0.20.1
Successfully installed excon-0.73.0
Successfully installed docker-api-1.34.2
Successfully installed declarative-option-0.1.0
Successfully installed declarative-0.0.10
Successfully installed uber-0.1.0
Successfully installed representable-3.0.4
Successfully installed retriable-3.1.2
Successfully installed mini_mime-1.0.2
Successfully installed jwt-2.2.1
Successfully installed signet-0.14.0
Successfully installed memoist-0.16.2
Successfully installed os-1.1.0
Successfully installed googleauth-0.10.0
Successfully installed google-api-client-0.34.1
Successfully installed train-3.2.28
Successfully installed train-habitat-0.2.13
Successfully installed jmespath-1.4.0
Successfully installed aws-partitions-1.303.0
Successfully installed aws-eventstream-1.1.0
Successfully installed aws-sigv4-1.1.2
Successfully installed aws-sdk-core-3.94.0
Successfully installed aws-sdk-apigateway-1.38.0
Successfully installed aws-sdk-apigatewayv2-1.19.0
Successfully installed aws-sdk-athena-1.24.0
Successfully installed aws-sdk-autoscaling-1.22.0
Successfully installed aws-sdk-budgets-1.28.0
Successfully installed aws-sdk-cloudformation-1.33.0
Successfully installed aws-sdk-cloudhsm-1.20.0
Successfully installed aws-sdk-cloudhsmv2-1.21.0
Successfully installed aws-sdk-cloudtrail-1.21.0
Successfully installed aws-sdk-cloudwatch-1.36.0
Successfully installed aws-sdk-cloudwatchlogs-1.29.0
Successfully installed aws-sdk-codecommit-1.31.0
Successfully installed aws-sdk-codedeploy-1.28.0
Successfully installed aws-sdk-codepipeline-1.29.0
Successfully installed aws-sdk-configservice-1.43.0
Successfully installed aws-sdk-costandusagereportservice-1.19.0
Successfully installed aws-sdk-dynamodb-1.45.0
Successfully installed aws-sdk-ec2-1.154.0
Successfully installed aws-sdk-ecr-1.26.0
Successfully installed aws-sdk-ecs-1.60.0
Successfully installed aws-sdk-efs-1.26.0
Successfully installed aws-sdk-eks-1.35.0
Successfully installed aws-sdk-elasticache-1.31.0
Successfully installed aws-sdk-elasticbeanstalk-1.28.0
Successfully installed aws-sdk-elasticloadbalancing-1.20.0
Successfully installed aws-sdk-elasticloadbalancingv2-1.41.0
Successfully installed aws-sdk-elasticsearchservice-1.33.0
Successfully installed aws-sdk-firehose-1.26.0
Successfully installed aws-sdk-iam-1.36.0
Successfully installed aws-sdk-kafka-1.19.0
Successfully installed aws-sdk-kinesis-1.21.0
Successfully installed aws-sdk-kms-1.30.0
Successfully installed aws-sdk-lambda-1.39.0
Successfully installed aws-sdk-organizations-1.17.0
Successfully installed aws-sdk-rds-1.83.0
Successfully installed aws-sdk-redshift-1.41.0
Successfully installed aws-sdk-route53-1.32.0
Successfully installed aws-sdk-route53domains-1.20.0
Successfully installed aws-sdk-route53resolver-1.12.0
Successfully installed aws-sdk-s3-1.63.0
Successfully installed aws-sdk-securityhub-1.23.0
Successfully installed aws-sdk-ses-1.28.0
Successfully installed aws-sdk-sms-1.18.0
Successfully installed aws-sdk-sns-1.22.0
Successfully installed aws-sdk-sqs-1.24.0
Successfully installed aws-sdk-ssm-1.73.0
Successfully installed train-aws-0.1.16
Successfully installed http-form_data-1.0.3
Building native extensions. This could take a while...
Successfully installed http_parser.rb-0.6.0
Successfully installed http-2.2.2
Building native extensions. This could take a while...
Successfully installed libyajl2-1.2.0
Building native extensions. This could take a while...
Successfully installed ffi-yajl-2.3.3
Successfully installed chef-utils-15.10.12
Successfully installed tomlrb-1.3.0
Successfully installed mixlib-config-3.0.6
Successfully installed fuzzyurl-0.9.0
Successfully installed chef-config-15.10.12
Successfully installed chef-telemetry-1.0.3
Successfully installed equatable-0.6.1
Successfully installed tty-color-0.5.1
Successfully installed pastel-0.7.3
Successfully installed tty-cursor-0.7.1
Successfully installed strings-ansi-0.2.0
Successfully installed unicode_utils-1.4.0
Successfully installed unicode-display_width-1.7.0
Successfully installed strings-0.1.8
Successfully installed tty-box-0.5.0
Successfully installed necromancer-0.5.1
Successfully installed wisper-2.0.1
Successfully installed tty-screen-0.7.1
Successfully installed tty-reader-0.7.0
Successfully installed tty-prompt-0.21.0
Successfully installed license-acceptance-1.0.19
Successfully installed thor-0.20.3
Successfully installed json-schema-2.8.1
Successfully installed method_source-0.9.2
Successfully installed rspec-support-3.9.2
Successfully installed rspec-core-3.9.1
Successfully installed diff-lcs-1.3
Successfully installed rspec-expectations-3.9.1
Successfully installed rspec-mocks-3.9.1
Successfully installed rspec-3.9.0
Successfully installed rspec-its-1.3.0
Successfully installed coderay-1.1.2
Successfully installed pry-0.12.2
Successfully installed hashie-3.6.0
Successfully installed mixlib-log-3.0.8
Successfully installed sslshake-1.3.0
Successfully installed parallel-1.19.1
Successfully installed tty-table-0.11.0
Successfully installed faraday_middleware-0.14.0
Successfully installed parslet-1.8.2
Successfully installed semverse-3.0.0
Successfully installed htmlentities-4.3.4
Successfully installed tins-1.24.1
Successfully installed term-ansicolor-1.7.1
Successfully installed inspec-4.18.51
160 gems installed
ERROR:  Could not find a valid gem 'cinc-auditor-bin' (= 4.18.51) in any repository
ERROR:  Possible alternatives: cinch-bitcoin, iAuditor, ip_auditor, mina-unicorn
The command '/bin/sh -c gem install --user-install --no-document --source ${GEM_SOURCE} --version ${VERSION} inspec &&     gem install --user-install --no-document --source ${GEM_SOURCE} --version ${VERSION} cinc-auditor-bin &&     gem install --user-install --no-document jsonl train-kubernetes &&     cinc-auditor plugin install train-kubernetes &&     sed -ie 's#"= 0#"0#g' /home/${RUNUSER}/.inspec/plugins.json' returned a non-zero code: 2
make: *** [build] Error 2`

**Comment by bgeesaman** [comment]
Thanks for the heads up!  Appears that the Cinc project removed their gems from rubygems.org and moved them over to packagecloud.io.  I've updated the Dockerfile to accommodate.
